// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4QrhMLaHlf9USpfPK5Gi6UFifC4g8gRc',
    appId: '1:1013893044546:web:1fe5b5e6d5ea6d012c10db',
    messagingSenderId: '1013893044546',
    projectId: 'telemedicine-4ae48',
    authDomain: 'telemedicine-4ae48.firebaseapp.com',
    storageBucket: 'telemedicine-4ae48.firebasestorage.app',
    measurementId: 'G-6K9H9H31E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbd5wObWqP25Gf0CcUUsJ9NGSUD1kRJlA',
    appId: '1:1013893044546:android:2fa2f67a6a07f3ee2c10db',
    messagingSenderId: '1013893044546',
    projectId: 'telemedicine-4ae48',
    storageBucket: 'telemedicine-4ae48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXapq8Kpb5FAVEsqoCos7yJZFt5Xk169E',
    appId: '1:1013893044546:ios:4f1f7ba9a2ee27952c10db',
    messagingSenderId: '1013893044546',
    projectId: 'telemedicine-4ae48',
    storageBucket: 'telemedicine-4ae48.firebasestorage.app',
    iosBundleId: 'com.example.telemedicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXapq8Kpb5FAVEsqoCos7yJZFt5Xk169E',
    appId: '1:1013893044546:ios:4f1f7ba9a2ee27952c10db',
    messagingSenderId: '1013893044546',
    projectId: 'telemedicine-4ae48',
    storageBucket: 'telemedicine-4ae48.firebasestorage.app',
    iosBundleId: 'com.example.telemedicine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4QrhMLaHlf9USpfPK5Gi6UFifC4g8gRc',
    appId: '1:1013893044546:web:e43cdd2adbe5d89b2c10db',
    messagingSenderId: '1013893044546',
    projectId: 'telemedicine-4ae48',
    authDomain: 'telemedicine-4ae48.firebaseapp.com',
    storageBucket: 'telemedicine-4ae48.firebasestorage.app',
    measurementId: 'G-PE7Q0YFVYF',
  );

}